name: biyahe_app
description: B.I.Y.A.H.E. Multi-modal Transit Engine
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  google_maps_flutter: ^2.5.0
  latlong2: ^0.9.0
  http: ^1.1.0
  provider: ^6.0.5
  mapbox_maps_flutter: ^0.4.0
  mapbox_navigation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
